
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-nas-production
spec:
    capacity:
      storage: 500Gi
    accessModes:
      - ReadWriteMany
    flexVolume:
      driver: "alicloud/nas"
      options:
        path: /api
        server: 69ce7499e7-gel50.cn-qingdao.nas.aliyuncs.com
        vers: "4.0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-claim-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv: pv-nas-production