
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-nas-production
spec:
    capacity:
      storage: 500Gi
    accessModes:
      - ReadWriteMany
    mountOptions:
      - vers=4.0
      - noresvport
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /api
      server: 69ce7499e7-gel50.cn-qingdao.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-claim-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv: pv-nas-production